### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Emmsii** [Emmsii/KeyKeeper#7]
- [ ] Add EffectsManager.
- [ ] Look into drawing everything to a small RenderTarget, [see](https://github.com/MrGrak/DungeonRun/blob/master/GameClasses/ScreenManager.cs).
- [ ] Fix mouse released logic in `Button` class.
- [x] Rename `InputEventArgs` class to `KeyEventArgs`.
- [x] Add background colors to sprites.

**Comment by Emmsii** [comment]
Background colours added in 02bc770.

**Comment by Emmsii** [comment]
Renamed `InputEventArgs` in 4a83090.
